import { Product } from "@/types";
import { random, range } from "lodash";

export function generateProducts(numFruits = 1000): Product[] {
    const colorRange = range(0, 10).map(() => {
        const randomColor = colorNames.splice(random(0, colorNames.length - 1), 1);
        if (randomColor.at(0)) {
            return randomColor[0];
        }
        return "red";
    });

    return range(0, numFruits).map((index) => {
        const sku = `SKU-${random(200, 400)}-${random(100, 400)}-${index}`;
        const numColorOptions = random(1, 5);
        const colors = new Set(range(0, numColorOptions).map(() => colorRange[random(0, colorRange.length - 1)]));
        return {
            index,
            label: fruitNames[random(0, fruitNames.length - 1)],
            sku,
            rating: random(1, 5),
            price: random(10, 100),
            image_color: colorNames[random(0, colorNames.length - 1)],
            colors: Array.from(colors),
        };
    });
}

const fruitNames = [
    "Abiu",
    "Açaí",
    "Acerola",
    "Akebi",
    "Ackee",
    "African Cherry Orange",
    "American Mayapple",
    "Apple",
    "Apricot",
    "Aratiles",
    "Araza",
    "Avocado",
    "Banana",
    "Bilberry",
    "Blackberry",
    "Blackcurrant",
    "Black sapote",
    "Blueberry",
    "Boysenberry",
    "Breadfruit",
    "Cactus pear",
    "Catmon",
    "Cempedak",
    "Cherimoya (Custard Apple)",
    "Cherry",
    "Chico fruit",
    "Citron",
    "Cloudberry",
    "Coco de mer",
    "Coconut",
    "Crab apple",
    "Cranberry",
    "Currant",
    "Damson",
    "Date",
    "Dragonfruit",
    "Pitaya",
    "Durian",
    "Elderberry",
    "Feijoa",
    "Fig",
    "Finger lime",
    "Caviar Lime",
    "Gac",
    "Goji berry",
    "Gooseberry",
    "Grape",
    "Raisin",
    "Grapefruit",
    "Grewia asiatica",
    "Guava",
    "Hala fruit",
    "Honeyberry",
    "Huckleberry",
    "Jabuticaba",
    "Jackfruit",
    "Jambul",
    "Japanese plum",
    "Jostaberry",
    "Jujube",
    "Juniper berry",
    "Kiwan",
    "Kiwifruit",
    "Kumquat",
    "Lanzones",
    "Lemon",
    "Lime",
    "Loganberry",
    "Longan",
    "Loquat",
    "Lulo",
    "Lychee",
    "Magellan Barberry",
    "Macopa",
    "Mamey apple",
    "Mamey Sapote",
    "Mango",
    "Mangosteen",
    "Marionberry",
    "Medlar",
    "Melon",
    "Cantaloupe",
    "Galia melon",
    "Honeydew",
    "Mouse melon",
    "Muskmelon",
    "Watermelon",
    "Miracle fruit",
    "Mohsina",
    "Momordica fruit",
    "Monstera deliciosa",
    "Mulberry",
    "Nance",
    "Nectarine",
    "Orange",
    "Blood orange",
    "Clementine",
    "Mandarine",
    "Tangerine",
    "Papaya",
    "Passionfruit",
    "Pawpaw",
    "Peach",
    "Pear",
    "Persimmon",
    "Pineapple",
    "Pineberry",
    "Plantain",
    "Plum",
    "Prune (dried plum)",
    "Plumcot",
    "Pomegranate",
    "Pomelo",
    "Quince",
    "Raspberry",
    "Salmonberry",
    "Rambutan",
    "Redcurrant",
    "Rose apple",
    "Salal berry",
    "Salak",
    "Santol",
    "Sapodilla",
    "Sapote",
    "Sarguelas",
    "Saskatoon",
    "Satsuma",
    "Sloe",
    "Soursop",
    "Star apple",
    "Star fruit",
    "Strawberry",
    "Sugar apple",
    "Suriname cherry",
    "Tamarillo",
    "Tamarind",
    "Tangelo",
    "Tayberry",
    "Thimbleberry",
    "Ugli fruit",
    "White currant",
    "White sapote",
    "Ximenia",
    "Yuzu;",
];

const colorNames = [
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgreen",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dodgerblue",
    "firebrick",
    "forestgreen",
    "fuchsia",
    "gold",
    "goldenrod",
    "green",
    "greenyellow",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgreen",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "rebeccapurple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "transparent",
    "turquoise",
    "violet",
    "wheat",
    "yellow",
    "yellowgreen",
];
